Buy/urls.py
from django.conf.urls import url
from django.urls import path
from Buy import views

app_name = 'Buy'

urlpatterns = [
	path(r'',views.index,name='index'),
	path(r'match/',views.match,name='match'),
	path(r'signup/',views.SignupFormView, name='signup'),
	path(r'login/',views.LoginFormView, name='login'),
	path(r'final/',views.finalPage, name='final_page')
]

eTicket/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Buy import views

urlpatterns = [
	path(r'',include('Buy.urls')),
    path('admin/', admin.site.urls),
]

Buy/models.py
from django.db import models

# Create your models here.
class User(models.Model):
	name = models.CharField(max_length=50)
	emailId = models.CharField(max_length=50,unique=True)
	password = models.CharField(max_length=50)
	def __str__(self):
		return self.name

class Stadium(models.Model):
	name = models.CharField(max_length=256)
	location = models.CharField(max_length=256)
	typeATotal = models.IntegerField(default=0)
	typeBTotal = models.IntegerField(default=0)
	typeCTotal = models.IntegerField(default=0)
	typeAPrice = models.IntegerField(default=0)
	typeBPrice = models.IntegerField(default=0)
	typeCPrice = models.IntegerField(default=0)
	def __str__(self):
		return self.name

class Match(models.Model):
	name = models.CharField(max_length=256,default='match')
	teamA = models.CharField(max_length=256)
	teamB = models.CharField(max_length=256)
	stadiumId = models.ForeignKey(Stadium,on_delete=models.CASCADE)
	date = models.DateTimeField('match_date')
	def __str__(self):
		return self.teamA+' vs '+self.teamB

class RemainingTickets(models.Model):
	matchId = models.ForeignKey(Match, on_delete=models.CASCADE)
	typeARemaining = models.IntegerField(default=0)
	typeBRemaining = models.IntegerField(default=0)
	typeCRemaining = models.IntegerField(default=0)
	
	def save(self, *args, **kwargs):
		# self.typeARemaining = self.matchId.stadiumId.typeATotal
		# self.typeBRemaining = self.matchId.stadiumId.typeBTotal
		# self.typeCRemaining = self.matchId.stadiumId.typeCTotal
		super().save(*args, **kwargs)

	def __str__(self):
		return self.matchId.name

class Ticket(models.Model):
	ticketType = models.CharField(max_length=10)
	price = models.IntegerField(default=0)
	userId = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
	matchId = models.ForeignKey(Match, on_delete=models.CASCADE, default=0)
	def __str__(self):
		return self.ticketType + ' : ' + str(self.price) + ' by ' + self.userId.name

Buy/forms.py
from django import forms
from django.core import validators

class SignupForm(forms.Form):
	name = forms.CharField(label='Name', max_length=100)
	email = forms.EmailField(label = 'Email',max_length=100)
	password = forms.CharField(label='Password', max_length=100)
	cpassword = forms.CharField(label='Confirm Password', max_length=100)
	botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, 
								validators=[validators.MaxLengthValidator(0)])

	def clean(self):
		allData = super().clean()
		p = allData['password']
		c = allData['cpassword']
		if p!=c:
			raise forms.ValidationError("Password and Confirm Password does not match!!")

	def raiseError(self):
		raise forms.ValidationError("Something went wrong!! Try again.")
	# def clean_botcatcher(self):
	# 	inp = self.cleaned_data['botcatcher']
	# 	if len(inp) > 0 :
	# 		raise forms.ValidationError("Gotcha Bot!!")

class LoginForm(forms.Form):
	email = forms.CharField(label='Email Id', max_length=100)
	password = forms.CharField(label='Password', max_length=100)

Buy/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from Buy.models import User, Stadium, Ticket, RemainingTickets,Match
from . import forms
import urllib.request, urllib.parse, urllib.error
import json


def buyTicket(uId, mId, sId, ty, count):
	ticketPrice = 0
	ticketType = 'Z'
	stadium = Stadium.objects.get(pk=sId)
	match = Match.objects.get(pk=mId)
	rTickets = RemainingTickets.objects.get(matchId=match)
	if ty == 'A':
		ticketType = 'A'
		ticketPrice = stadium.typeAPrice
		rTickets.typeARemaining = rTickets.typeARemaining - int(count)
	elif ty =='B':
		ticketType = 'B'
		ticketPrice = stadium.typeBPrice
		rTickets.typeBRemaining = rTickets.typeBRemaining - int(count)
	elif ty =='C':
		ticketType = 'C'
		ticketPrice = stadium.typeBPrice
		rTickets.typeCRemaining = rTickets.typeCRemaining - int(count)
	user = User.objects.get(pk=uId)
	t = Ticket(ticketType=ticketType, price=ticketPrice, userId=user, matchId=match)
	t.save()
	rTickets.save()


# Create your views here.

def index(request):
	url = "https://api.sportradar.com/hockey-t1/field/en/schedules/2016-08-12/schedule.json?api_key=326z6yburw4zx97wb5r6e4s3"
	fhand = urllib.request.urlopen( url ).read()
	jso = json.loads(fhand)
	lst = jso["sport_events"]
	newlst = list()
	i=1
	for l in lst:
		dct = {}
		dct["pk"]=i
		i+=1
		dct["team1"] = l["competitors"][0]["country"]
		dct["team2"] = l["competitors"][1]["country"]
		newlst.append(dct)
		print(dct)
	all_matches = {'matches': newlst }
	return render(request,'Buy/index.html',all_matches)

def match(request):

	mId = request.GET.get('matchid')
	m = Match.objects.get(pk=mId)
	st = m.stadiumId
	rem = RemainingTickets.objects.get(matchId=mId)

	lat = "5"+str(mId)
	lon = "2"+str(mId)

	url = "http://api.weatherunlocked.com/api/current/"+lat+","+lon+"?app_id=fff7371d&app_key=13fbda8c8662ff436fa16f1f01aae96e"
	req = urllib.request.Request(url)
	req.add_header("Accept","application/json")
	fhand = urllib.request.urlopen( req ).read()
	jso = json.loads(fhand)
	wthr_dsc = jso["wx_desc"]
	temperature = jso["temp_c"]


	dic = {"match" : m,
			"stadium" : st,
			"rem" : rem,
			"wthr_dsc" : wthr_dsc,
			"temperature" : temperature
			}
	return render(request,'Buy/match.html',dic)

def SignupFormView(request):
	form = forms.SignupForm()
	mId=request.GET.get('matchid')
	sId=request.GET.get('sid')
	ty = request.GET.get('type')
	count = request.GET.get('count')

	if request.method == 'POST':
		form = forms.SignupForm(request.POST)

		if form.is_valid():
			# DO SOMETHING CODE
			print("VALIDATION SUCCESS!")
			n = form.cleaned_data['name']
			em = form.cleaned_data['email']
			pas = form.cleaned_data['password']
			u = User(name=n, emailId=em, password=pas)
			u.save()
			buyTicket(u.pk, mId, sId, ty,count)
			return redirect('/final/')
		else:
			forms.SignupForm.raiseError()

	return render(request,'Buy/signup.html',{'form':form})

def LoginFormView(request):
	form = forms.LoginForm()
	mId=request.GET.get('matchid')
	sId=request.GET.get('sid')
	ty = request.GET.get('type')
	count = request.GET.get('count')
	
	if request.method == 'POST':
		form = forms.LoginForm(request.POST)
		form.is_valid()
		u = User.objects.get(emailId = form.cleaned_data['email'])
		if u.password == form.cleaned_data['password']:
			buyTicket(u.pk, mId, sId, ty,count)
			return redirect('/final/')
			#return render(request, 'Buy/final.html',{'name' : u.name})

		else:
			dic = {
				'form' : form,
				'matchid' : mId,
				'sid' : sId,
				'type' : ty,
				'count' : count,
				'error' : 'yes'
			}
			return render(request, 'Buy/login.html',dic)

	dic = {
			'form' : form,
			'matchid' : mId,
			'stadiumid' : sId,
			'ty' : ty,
			'error' : 'no'
	}
	return render(request, 'Buy/login.html',dic)

def finalPage(request):

	return render(request,'Buy/final.html',{})

Buy/templates/Buy/final.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  {% load static %}
  <title>Confirmation Page</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">
  <style>
  body{
      margin: 0 auto;
      padding: 0;
    background-image: linear-gradient(to right top, #051937, #004d7a, #008793, #00bf72, #a8eb12);
  }
  h1, h2{
      text-align: center;
  }
  img{
      margin: 7% 46.5%;
      max-width: 100px;
  }
  .button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin-top: 2%;
    cursor: pointer;
    border-radius: 12px;
}
  .text2{
      margin-bottom: 700px;
  }
  </style>
</head>
<body>
    <form method="get" action="{% url 'Buy:index' %}">
      <button class = "button">Home Page</button>
    </form>
    <img src="{% static 'Buy/tick.png' %}">
    <h1>Thank you for Booking!!</h1>
    <h2 class="text2">Your Ticket is Booked!!</h2>


</body>
</html>

Buy/templates/Buy/index.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box;}
body {font-family: Verdana, sans-serif;
    background-image: linear-gradient(to right top, #051937, #004d7a, #008793, #00bf72, #a8eb12);}
.mySlides {display: none;}
img {vertical-align: middle;}

.headingText{
    text-align: center;
    font-size: 48px;
    color: white;
}
/* Slideshow container */
.slideshow-container {
  max-width: 500px;
  position: relative;
  margin: auto;
}

.button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 50px 80px 250px;
    cursor: pointer;
}
.button1{
    margin-left: 300px;
}
.button4 {border-radius: 12px;}

.button-div{
    float: left;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active {
  background-color: #717171;
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 1.5s;
  animation-name: fade;
  animation-duration: 1.5s;
}

@-webkit-keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .text {font-size: 11px}
}
</style>
</head>
<body>

<h2 class = "headingText">Hockey Ticket Booking Application</h2>

<div class="slideshow-container">

<div class="mySlides fade">
  <div class="numbertext">1 / 3</div>
  <img src="{% static 'Buy/image1.jpeg' %}" style="width:100%">
</div>

<div class="mySlides fade">
  <div class="numbertext">2 / 3</div>
  <img src="{% static 'Buy/image2.jpeg' %}" style="width:100%">
</div>

<div class="mySlides fade">
  <div class="numbertext">3 / 3</div>
  <img src="{% static 'Buy/image3.jpeg' %}" style="width:100%">
</div>

</div>
<br>

<div style="text-align:center">
  <span class="dot"></span> 
  <span class="dot"></span> 
  <span class="dot"></span> 
</div>

<form method="get" action="{% url 'Buy:match' %}">
<div class="button-div button1">
	{% for m in matches %}
    	<button class='button button4' name="matchid" value='{{m.pk}}' type="submit">{{m.team1}} vs {{m.team2}}</button>
  {% endfor %}
<!-- <button class="button button4 button1">India vs Australia</button>
<button class="button button4">India vs Pakistan</button>
<button class="button button4">Pakistan vs Australia</button> -->
</div>
</form>

<script>
var slideIndex = 0;
showSlides();

function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    for (i = 0; i < slides.length; i++) {
       slides[i].style.display = "none";  
    }
    slideIndex++;
    if (slideIndex > slides.length) {slideIndex = 1}    
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";  
    dots[slideIndex-1].className += " active";
    setTimeout(showSlides, 2000); // Change image every 2 seconds
}
</script>

</body>
</html>

Buy/templates/Buy/login.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;
    background-image: linear-gradient(to right top, #051937, #004d7a, #008793, #00bf72, #a8eb12);}
}
form {border: 3px solid #f1f1f1;}

input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}

.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

.container {
    padding: 16px;
    width: 35%;
    height: 880px;
    margin-left: 32.5%;
    margin-right: 32.5%;
    margin-top: 10%;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
</style>
</head>
<body>
<div class="container">
	<form method="POST">
        <h2>Login Form</h2>
        {{ form.as_p }}
	    {% csrf_token %}
    	<button type="submit">Login</button>
    	<p>Don't have an account ?</p>
	</form>
	<form method="GET" action="{% url 'Buy:signup' %}">
		<input type="hidden" name="matchid" value="{{matchid}}">
		<input type="hidden" name="sid" value="{{stadiumid}}">
		<input type="hidden" name="type" value="{{ty}}">
		<button>Sign Up</button>
	</form>
</div>

	

</body>
</html>

Buy/templates/Buy/match.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Verdana, sans-serif;
    background-image: linear-gradient(to right top, #051937, #004d7a, #008793, #00bf72, #a8eb12);}
.mySlides {display: none;}
img {vertical-align: middle;}

.headingText{
    text-align: center;
    font-size: 48px;
    color: white;
    margin: 20px auto;
}

.headingText2{
    text-align: center;
    font-size: 22px;
    color: white;
    margin: 10px auto 30px;
}
.span1{
    color: #051937;
}
.button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 10%;
    cursor: pointer;
    border-radius: 12px;
}
.image-left{
    float: left;
    width: 45%;
    margin: 2.5%;
}
.text-right{
    float: left;
    width: 40%;
    padding: 5%;
}
.tickets{
    width: 80%;
    margin: auto 10%;
    border: #051937 solid ;
    border-radius: 5%;
}

</style>
</head>
<body>

<h2 class = "headingText">{{ match }}</h2>
<h4 class = "headingText2">{{ match.date }}</h4>
<h4 class = "headingText2">Weather is {{ wthr_dsc }} with {{ temperature }} &#176; celcius</h4>


<div class="image-left">
  <img src="{% static 'Buy/image1.jpeg' %}" style="width:100%">
</div>
<div class="text-right">
        <h4 class = "headingText2">Stadium: <span class="span1">{{ stadium }}</span></h4>
        <h4 class = "headingText2">Venue: <span class="span1">{{ stadium.location }}</span></h4>
        <div class = "tickets">
            <h4 class = "headingText2">Tickets</h4>
            <form method="GET" action="{% url 'Buy:login' %}">
            		<input type="hidden" name="matchid" value="{{match.pk}}">
                    <input type="hidden" name="sid" value="{{stadium.pk}}">
                    <input name="count">
            	<div class = "ticketType-left">
					<button class = "button" name="type" value="A" type="submit">GOLD CLASS</button>{{rem.typeARemaining}}
					<button class = "button" name="type" value="B" type="submit">SILVER CLASS</button>{{rem.typeBRemaining}}
					<button class = "button" name="type" value="C" type="submit">BRONZE CLASS</button>{{rem.typeBRemaining}}
            	</div>
            </form>
            <div class = "ticketType-right"></div>
        </div>


</div>

</body>
</html>

Buy/templates/Buy/signup.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;
    background-image: linear-gradient(to right top, #051937, #004d7a, #008793, #00bf72, #a8eb12);}
}
form {border: 3px solid #f1f1f1;}

input[type=text], input[type=password] , input[type=email]{
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}

.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

.container {
    padding: 16px;
    width: 35%;
    height: 880px;
    margin-left: 32.5%;
    margin-right: 32.5%;
    margin-top: 10%;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
</style>
</head>
<body>
<div class="container">
	<form method="POST">
        <h2>Sign Up Form</h2>
        {{ form.as_p }}
	    {% csrf_token %}
    	<button type="submit">Signup</button>
	</form>
</div>

</body>
</html>